### ISSUE TITLE
Wrong path for ACPI actions?

### ISSUE THREAD

**Issue by simonvanderveldt** [tokiclover/hprofile#1]
Hi @tokiclover,

I'm not sure if they are really wrong since I don't use them but it seems the ACPI event contain the wrong path to the matching actions.
https://github.com/tokiclover/hprofile/blob/master/acpi/events/power#L7
It seems to me `action` should be `actions`.

Also, small question, does the installation of these files mean that the matching `hprofile` commands are being triggered?

**Comment by tokiclover** [comment]
That's just a typo, the file is actually installed to _/etc/acpi/{events,actions}_.
If ACPI is functional, the actions should follow. Of course you're free to remove an file. That's just a convenient to have a _power_ profile when AC is on/off.
